SELECT Id
     , Anvil__DealerStockNumber__c
     , Anvil__Description__c
     , Anvil__Status__c
     , Anvil__Group__c
     , Anvil__ModelYear__c
     , Anvil__EquipmentMake__c
     , Anvil__EquipmentModel__c
     , Anvil__SerialNumber__c
     , Anvil__EquipmentType__c
     , Anvil__Sub_Group__c
     , Anvil__Variant__c
     , Anvil__Hours_or_Units__c
     , Anvil__Seperator_Hours__c
     , Adv_Ready_Checked_Date__c
     , Anvil__Store__c
     , Anvil__OrderDate__c
     , Anvil__e189_Traded_By__c
     , Anvil__PurchaseDate__c
     , Anvil__Basic_Warranty_Hours__c
     , Anvil__Basic_Warranty_End_Date__c
     , Anvil__Extended_Warranty_Hours__c
     , Anvil__Extended_Warranty_End_Date__c
     , Anvil__Invoice_Amount__c
     , Anvil__SalesPrice__c
     , Anvil__NetSalesPrice__c
     , Anvil__DateReceived__c
     , Anvil__E_SalesInvoiceNo__c
     , Anvil__SalesDate__c
     , Anvil__Sold_By__c
     , Anvil__Account__c
     , Anvil__Description_V2__c
     , Anvil__Year_Manufactured__c
     , Anvil__Traded_In_For__c
     , Anvil__Previous_Owner__c
FROM Anvil__DealerStockUnit__c  