SELECT Id
     , Anvil__Account__c
     , Anvil__Buyer_ID__c
     , Anvil__County__c
     , Anvil__State__c
     , Anvil__Zip__c
     , Anvil__FIPS__c
     , Anvil__DUNS_Number__c
     , Anvil__SIC__c
     , Anvil__SIC_Description__c
     , OwnerId
FROM Anvil__EDA_Buyer__c  