SELECT Id
     , Anvil__Account__c
     , Anvil__QuoteId__c
     , Anvil__WorkflowStatus__c
     , Anvil__JDQ_Status__c
     , Anvil__JDQuote__c
     , MUD_Master_PO__c
     , Anvil__marketUse__c
     , Anvil__transactionType__c
FROM Anvil__PurchaseOrder__c
