SELECT Id
     , Anvil__Account__c
     , Anvil__QuoteId__c
     , Anvil__WorkflowStatus__c
     , Anvil__Equipment_Stock_Numbers__c
     , Anvil__JDQ_Status__c
     , Anvil__JDQuote__c
     , Anvil__marketUse__c
     , Anvil__transactionType__c
     , Anvil__Owner_Id__c
     , Anvil__Invoicing_Date__c
     , CreatedDate
     , Anvil__POAmount__c
FROM Anvil__PurchaseOrder__c