SELECT Id
     , Anvil__Account__c
     , Anvil__FiscalYear__c
     , Anvil__e_Parts2__c
     , Anvil__e_Service2__c
     , Anvil__e_Rental__c
     , Anvil__e_Sales__c
     , Anvil__e_Total_Rev__c
FROM Anvil__Account_Sales_History__c 