SELECT Id
     , Name
     , Anvil__WorkOrderNumber__c
     , Anvil__Customer_Equipment__c
     , Anvil__DealerStockUnit__c
     , Anvil__e_Progress_Status__c
     , Anvil__e_Progress_Status_Description__c
     , Anvil__TotalSegments__c
     , Anvil__e_Stock_Or_Equipment__c
     , Anvil__Account__c
     , Anvil__e_Open_Date__c
     , Anvil__e_Close_Date__c
     , Anvil__e_Make__c
     , Anvil__e_Model__c
     , Anvil__MachineSerialNumber__c
     , Anvil__e_Invoice_Service_Value__c
     , Anvil__Branch__c
FROM Anvil__ServiceWorkOrder__c 