SELECT Id
     , AccountId
     , OwnerId
     , CreatedDate
     , ActivityDate
     , CallObject
     , Subject
     , CallDisposition
     , TaskSubtype
     , Description
     , Status
     , Priority
     , CallType
FROM Task 
