SELECT Id
     , Anvil__Account__c
     , Anvil__FiscalYear__c
     , Anvil__PartsSales__c
     , Anvil__ServiceSales__c
     , Anvil__RentalSales__c
     , Anvil__WholegoodSales__c
     , Anvil__TotalSales__c
FROM Anvil__Account_Sales_History__c 